
function Contact() {
  return (
    <>
    <div className="px-5"> 
                      <h1>I am the Contact page </h1>
                      <p className="text-red-600">Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolor obcaecati fuga sapiente saepe officia quae exercitationem dolorem aspernatur quisquam temporibus corrupti tenetur accusamus explicabo, at aperiam repudiandae beatae, iste voluptate ut sint molestias ea. Tempore odit provident, hic pariatur incidunt eveniet sequi fuga consectetur magni aliquam numquam quos minima harum sunt? Unde officia voluptas odit harum perferendis maiores sequi, dicta quia ex veritatis reprehenderit corporis deleniti cumque cum libero id distinctio eaque hic. Maiores ipsam soluta illum repudiandae libero officia rem, architecto et iste alias eligendi suscipit culpa error laboriosam, velit ipsa omnis dicta unde. Distinctio debitis consequatur perspiciatis, id maxime, reprehenderit obcaecati unde optio, placeat quasi molestias. Eius tenetur, sed officia ipsum libero ut eveniet ex incidunt quasi magni commodi iste quia hic itaque vel esse veniam dolorum cum numquam veritatis facere! Perspiciatis dolor, delectus quam unde sit praesentium quidem voluptate ratione soluta rem distinctio, id quos, saepe dolorem omnis totam architecto porro atque at! Magnam quasi veniam soluta omnis sit. Perferendis consequatur hic voluptatem ducimus non suscipit? Sunt incidunt deleniti unde repudiandae. Laboriosam aperiam debitis dolores blanditiis sunt sed minus dolorem et nesciunt veritatis, accusamus iure fugiat tempora natus soluta eum! Optio cupiditate excepturi sequi ipsa exercitationem? Tempora, omnis eveniet, iure molestias laboriosam deleniti dolores eos illum ab ea assumenda saepe modi nihil nam officia rem. Beatae suscipit unde omnis ad ut numquam, facere quibusdam, non nulla inventore quas quasi! Odit natus similique ipsam necessitatibus beatae vero delectus nemo? Explicabo vel cum quo voluptate eos nisi commodi, iure voluptas vero modi harum. Consectetur, magnam pariatur cum enim consequuntur libero quas cupiditate, nemo, fugiat accusantium facilis sit! Minus possimus placeat culpa unde maiores aspernatur ullam? Minus excepturi quas, praesentium beatae nam odio maiores aperiam, perferendis ex asperiores eligendi qui, modi error maxime veritatis earum dolorem fugiat quam magni eius?</p>
                  </div>
  </>
  )
}

export default Contact